version: "3.4"

services:
  db_acqua:
    image: postgres:alpine
    ports:
      - 4321:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=appone
      - POSTGRES_PASSWORD=wearechampions
      - POSTGRES_DB=appone
    volumes:
      - db_data:/var/lib/postgresql/data/
  api_acqua:
    image: api
    build:
      context: .
      dockerfile: ./Dockerfile
    command: flask run --host 0.0.0.0
    ports:
      - 5000:5000
      - 3000:3000
    expose:
      - 5000
    depends_on:
      - db_acqua
    env_file:
      - ./.env
    volumes:
      - ./:/app
volumes:
  db_data:
